CALCULATORS = [
    {
        "name": "Složené úročení",
        "slug": "slozene-uroceni",
        "category": "Investice",
        "tags": ["Finance", "Růst investice", "Inflace"],
        "description": "Spočítej růst investice, pravidelné vklady, zisk i reálnou hodnotu po započtení inflace.",
        "href": "compound_interest",
        "status": "Dostupné nyní",
    },
    {
        "name": "Čistá mzda v ČR",
        "slug": "cista-mzda",
        "category": "Mzdy a práce",
        "tags": ["Mzda", "Daně", "Pojištění"],
        "description": "Spočítej čistou mzdu podle typu pracovního vztahu, slev, dětí, ZTP/P, invalidity a minima zdravotního pojištění.",
        "href": "net_salary",
        "status": "Dostupné nyní",
    },
    {
        "name": "Hypotéka",
        "slug": "hypoteka",
        "category": "Bydlení",
        "tags": ["Hypotéka", "Splátka", "Úrok"],
        "description": "Spočítej měsíční splátku hypotéky, celkové přeplacení, podíl vlastních zdrojů a průběh splácení v čase.",
        "href": "mortgage",
        "status": "Dostupné nyní",
    },
    {
        "name": "Mateřská",
        "slug": "materska",
        "category": "Rodina",
        "tags": ["PPM", "Mateřská", "DVZ"],
        "description": "Orientační výpočet peněžité pomoci v mateřství podle hrubé mzdy, typu péče a počtu dětí.",
        "href": "maternity",
        "status": "Dostupné nyní",
    },
    {
        "name": "Rodičovská",
        "slug": "rodicovska",
        "category": "Rodina",
        "tags": ["Rodičovský příspěvek", "Limit", "Čerpání"],
        "description": "Spočítej celkovou částku rodičovského příspěvku, měsíční limit a orientační délku čerpání.",
        "href": "parental",
        "status": "Dostupné nyní",
    },
    {
        "name": "Nemocenská",
        "slug": "nemocenska",
        "category": "Rodina",
        "tags": ["Nemocenská", "Neschopenka", "DVZ"],
        "description": "Orientační výpočet nemocenské od 15. dne neschopnosti podle hrubé mzdy a délky trvání.",
        "href": "sickness",
        "status": "Dostupné nyní",
    },
]
